### ISSUE TITLE
long-term plans

### ISSUE THREAD

**Issue by duckinator** [duckinator/inq#145]
I'll provide my own thoughts on this in comments. This is from @indirect on Slack (https://bundler.slack.com/archives/how_is/p1487225983811281):

> how_is vision document
>
> In some future and ideal day, I would love to be able to use how_is to provide detailed reporting on the state of any open source project, directly aimed at helping maintainers cope with the vast influx of project stuff going on at any given time, especially for projects that are spread across multiple repos.
>
> The closest thing I have ever seen to this in the past is the Docker project's OSS project monitoring stack. Unfortunately, they use the ELK (elastic search, logstash, kibana) stack as their way of collecting and visualizing this data, and that's both too heavyweight and too hard to operate, maintain, and update for me.
>
> there are a few phases that I can imagine how_is going through on its way to providing the entire vision that I have. I expect each phase would be built on top of the existing functionality of the phase before, providing more and more functionality over time.
>
> phase 1: how_is monthly reports. the biggest benefit this offers me is helping to speed up the information-gathering step for Ruby Together monthly reports. at the end of this phase, I am imagining that we will have a running database-backed webapp. it will capture at least one set of monthly stats on the last day of every month, and save that data to the database. then, on the web frontend, I can choose which monthly report I would like to see, and view that report.
>
> I'm going to name the next two phases Breadth and Depth because I don't think they have an order or dependencies on one another.
>
> phase Breadth: how_is analytics. by the time this phase is complete, I am imagining being able to choose any date range and view a how_is report for that date range. that will require capturing and storing all the relevant stats at least once per day, and then querying for the given date range and presenting that data.
>
> phase Depth: increase the number of data points we are capturing. some of this is already present on github's pulse page, but we should be snapshotting the data for later reference. off the top of my head, I think this should include oldest open ticket, number and list of tickets with no comments that month, opened that month, and closed that month. number of PRs, number opened, merged, and closed. code changes, including authors, commits, additions, and deletions. a graph of open issues by label. a graph of releases vs issues being opened. a count of releases during the month, and whether they were major, minor, or tiny.
>
> Since I'm on a naming roll, why not: the last phase is Final Boss.
>
> phase Final Boss: a complete product that we can supply to the Ruby (and other OSS) community. by the end of this phase, I am imagining that we will have implemented a great visual design, provided by a designer and/or UXer. I expect we'll have fine-tuned the "what happened last month" report to the point where it's great, and useful for any open source project that wants to write summaries or reports. I'm also imagining that we will provide a "what should I look at now?" dashboard with the most typically useful and actionable information for an open source project, helping maintainers have the biggest positive impact with their limited time.

**Comment by duckinator** [comment]
## Phase 1

Any objections to this being the _first_ day of every month? That'll probably be a lot easier to implement.

## Breadth

IMO, tracking things over time is going to be the core feature of the dashboard. (My way of looking at it is that automating report generation is a stepping stone to tracking things over time, not an inherent goal in itself.) My thoughts on this are basically have a date range selector similar to Google Analytics' &mdash; pick the beginning date and end date from a calendar, and have a way to select granularity (daily, weekly, monthly).

## Depth

I think switching from scraping pulse data to using the API may help a lot with this. There's also possibly information from Code Climate (see also https://github.com/how-is/how_is/issues/12, [how-is/dashboard wiki](https://github.com/how-is/dashboard/wiki#dashboard-contents)).

Need to pull some of your ideas out into issues, for implementing specific features.

## Final Boss

The `Final Boss` phase sounds a lot like my long-term ideas that I wrote down somewhere a while back, but can't find.

One of the ideas I had was to automatically determine a problem area (growing number of issues, growing number of PRs, large number of old PRs, large number of old issues, etc), and offer a (hard-coded, not dynamic) actionable list of steps that may improve that problem area.

**Comment by duckinator** [comment]
@indirect, thoughts?

**Comment by indirect** [comment]
@duckinator cool, sounds like we are pretty much on the same page here! breaking this down into manageable tasks that move us forward is probably the next hard part. I'm happy to schedule some time to work with you on that. 👍

**Comment by duckinator** [comment]
This project changed a lot while it was worked on, and if inq dev ever picks back up it'll probably change even more. I'd expect much of these long-term plans to be irrelevant in such a scenario. Closing.
