### ISSUE TITLE
Rename to inq

### ISSUE THREAD

**Issue by duckinator** [duckinator/inq#258]
I am considering, prior to releasing v25.0, renaming how_is. Waiting for feedback from a few folks, prior to doing so.

**Comment by igalic** [comment]
to what?
or are you looking for suggestions?

**Comment by duckinator** [comment]
@igalic I'm leaning towards "inq" (short for "inquire"). This issue is mostly here for the purpose of including it in the milestone/reminding me to check back with a few particular people.
