### ISSUE TITLE
Question: More specific dates?

### ISSUE THREAD

**Issue by bronzdoc** [duckinator/inq#281]
Hey @duckinator :)

It is possible to pass different intervals to `inq`? i.e generating a report from two dates intervals?

My use case is that I want to generate the report `form` a specific date `to` another date.

**Comment by duckinator** [comment]
hi! It doesn't currently support that, _but_ it shouldn't be too difficult to add.

I think making [`Inq::Report.new(config, end_date)`](https://github.com/duckinator/inq/blob/master/lib/inq/report.rb#L17-L33) accept an end _or_ a date range would be enough from the API side of things.

At that point, it'd just be a matter of figuring out how to adjust the command line for it. Perhaps if the `--date` flag includes `..` it could be treated as a range, something like `--date 2018-01-01..2018-12-31`?
