### ISSUE TITLE
Add CI service sources

### ISSUE THREAD

**Issue by duckinator** [duckinator/inq#285]
- [x] Appveyor
- [x] Travis CI
- [ ] Circle CI ([API v1 Reference](https://circleci.com/docs/api/v1-reference/))
- [ ] Cirrus CI ([API Documentation](https://cirrus-ci.org/api/))
- [ ] GitHub Actions

**Comment by olleolleolle** [comment]
Would GitHub Actions make the list?

**Comment by duckinator** [comment]
yeah, definitely. added. :+1:
